name: Angular Auto Deploy to GitHub Pages

on:
  push:
    branches:
      - dev  # Deploy when pushing to dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular Browser app
        run: |
          npx ng build --configuration production --output-path=dist/browser \
            --base-href="https://SwathiSherigar.github.io/Pharmacy_billing_angular/"

      - name: Create 404 fallback
        run: cp dist/browser/index.html dist/browser/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/browser
          publish_branch: gh-pages
          keep_files: true
