name: Angular Auto Deploy to GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular Browser App
        run: npx ng build --configuration production

      - name: List dist folder contents
        run: ls -R dist

      - name: Create 404 fallback
        run: |
          if [ -f dist/pharma-talewind/browser/index.html ]; then
            cp dist/pharma-talewind/browser/index.html dist/pharma-talewind/browser/404.html
          else
            echo "index.html not found!"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/pharma-talewind/browser
          publish_branch: gh-pages
          keep_files: true
